### PR TITLE
fix(buffer): bufname conflict when creating a new buffer

### PR DESCRIPTION
**Pull request by archilkarchava**
Remove buffers for disposed editors before creating new buffers to avoid naming conflicts.

Fixes https://github.com/vscode-neovim/vscode-neovim/issues/1651

### Before the fix
https://github.com/vscode-neovim/vscode-neovim/assets/16840190/f8188db1-2e18-4eab-9422-21c6a02a7fba

### After the fix
https://github.com/vscode-neovim/vscode-neovim/assets/16840190/3bef4d45-a0fa-4b5e-a9bd-bfce1b606c9f

### CODE REVIEW

**Review by xiyaowong — APPROVED** [review]

**Comment by xiyaowong** [comment]
nice, I also encountered this error recently

**Comment by xiyaowong** [comment]
Tested, it works.

**Comment by fiddler** [comment]
This seems to break <c-^> - so jumping between the two last open buffers stopped working after installing 1.1.4. Installing 1.1.3 makes <c-^> work again normally. However, I'm not sure if it's related to my setup. I've configured it with `nnoremap <Leader><Leader> <c-^>` in my init.vim. Does this happen for you guys as well?

**Comment by xiyaowong** [comment]
@fiddler You mean <C-^> was normal before?

**Comment by fiddler** [comment]
Yup! It works for me on 1.1.3, but after updating to 1.1.4, it no longer works. It looks like it jumps inside the buffer instead of jumping to the other buffer - see the attached video.

https://github.com/vscode-neovim/vscode-neovim/assets/477113/5e591155-8984-4aac-929b-f34947a29210

PS. I noticed that directly using <c-^> in my VS Code does not work at all, but using it via the `nnoremap <Leader><Leader> <c-^>` binding works fine on 1.1.3 as shown in the video.

**Comment by xiyaowong** [comment]
Not sure. From the internal implementation of vscode-neovim(The management and switching of window and buffer should be performed by vscode), C-^ should not work properly. It was a coincidence that it worked normally before.

---

Possibly relevant code:
https://github.com/vscode-neovim/vscode-neovim/blob/50e3692ec40fe9edb42f6bef02f5de23dfe607f0/vim/vscode-neovim.vim#L101
https://github.com/vscode-neovim/vscode-neovim/blob/50e3692ec40fe9edb42f6bef02f5de23dfe607f0/src/buffer_manager.ts#L306-L310

**Pull request merged**
