### PR TITLE
feat(keymap): support ctrl+r numpad commands in insert mode

### PR DESCRIPTION
**Pull request by DiogoDoreto**
This PR adds support to pasting from registers while in insert mode using NumPad keys.

### CODE REVIEW

**Comment by DiogoDoreto** [comment]
@justinmk yeah, for now I think that's the only solution. When #886 gets completed then we should be able to simplify it.

**Comment by theol0403** [comment]
Thanks for the PR! #886 will indeed make this unnecessary, but I need to find the time to refactor the controller to make the PR work.

**Comment by theol0403** [comment]
If you have the time, can you fix the merge conflicts by rebasing? Nothing major, I think all that changed was using `shift+` instead of `shift-` for consistency. I'll fix myself once I have the time if it isn't done.

**Comment by theol0403** [comment]
Closed in favor of https://github.com/vscode-neovim/vscode-neovim/pull/886. Thanks anyway!
Please test it to see if it works for you.

**Pull request closed without merging**
