### PR TITLE
Fix b on long lines

### PR DESCRIPTION
**Pull request by zbw8388**
Solves #773 and partially addresses #573.

Somehow a sequence of cursorMove commands is causing a bug in vscode. Removing them and directly setting the cursor location solves this issue. We don't need cursorMove vscode commands in this case anyways as less than one line move does not seem to get registered in jumplist.

Since the extension is getting highlights from redraw notifications, which is limited by window size, and neovim did not make the starting column of the current viewport in buffer available in the drawing notifications, the visual mode still displays incorrectly in vscode. However, it seems like the actual editing itself is working properly. There is no good fix to this other than implementing the display part of visual mode in the extension.

### CODE REVIEW

**Comment by justinmk** [comment]
The deleted code sure looks attractive :) 

Possible to write some sort of test? At least to exercise the codepath.

Rebasing will fix CI.

**Comment by theol0403** [comment]
I've been using this for a while and it seems to work well. In addition, I think the codepath is already excersized by tests because it is a core part of the plugin. I think it also fixes a bug where lots of j/k up and down on the end of the line won't return to the same col after a bit.

**Review by theol0403 — APPROVED** [review]
There *might* be a slight performance decrease when holding j/k, but I'm having a lot of trouble being sure. I think it's acceptable.

**Comment by theol0403** [comment]
Additionally, I think this fixes a problem where some jumps don't get registered in jumplist, because they come from a sequence of cursormove commands.

**Pull request merged**
