### PR TITLE
fix: detect potential module conflicts

### PR DESCRIPTION
**Pull request by xiyaowong**

### CODE REVIEW

**Review by ollien — APPROVED** [review]

**Comment by ollien** [comment]
Could we stand to add this limitation to the docs somewhere?

**Comment by xiyaowong** [comment]
The documentation clearly states `local vscode = require("vscode")`. New users should understand this, but it may pose an issue for existing users.

**Comment by ollien** [comment]
I don't know that I would take away from that blurb that having a file called `lua/vscode.lua` in my configuration directory would pose a problem.

**Comment by xiyaowong** [comment]
I think it's enough to just detect errors. It seems a bit redundant to emphasize not using the same module name while already informing the user that the module name is vscode. Also, no plugin does it this way.

**Pull request merged**
