### PR TITLE
feat: sync nvim selection with vscode selection

### LINKED ISSUE #958: [FR] Convert Neovim selections to VSCode selections for every keystroke in visual mode
I tried `map q <cmd>call VSCodeNotifyVisual('noop', 1)<cr>` in `init.vim`, then every time I press `q` in visual mode, the nvim selections will be converted to vscode selections, I think this definitely could be automated. If it's implemented, [the selection sync issue](https://github.com/vscode-neovim/vscode-neovim/issues/778) will be resolved.

### PR DESCRIPTION
**Pull request by wenfangdu**
This solves the selection issue mostly (opt-in), there's a lot of room for improvements, please edit it if you see fit.

I have to say this is a pretty hacky solution and sometimes unreliable.

closes #958

### CODE REVIEW

**Comment by theol0403** [comment]
Looks interesting, I'm not sure how robust of a solution this is though.

A few thoughts:
- extract the config option as a parameter (like the others), it's not performant to ask for settings every time
- is it updating the highlights even when no highlight is updated? This seems questionable to trigger on typing.

**Comment by theol0403** [comment]
Also, I don't think this will work for column selection, as the SendSelection only sends a start/end hl pos.

**Comment by theol0403** [comment]
This will also still be vulnerable to https://github.com/vscode-neovim/vscode-neovim/issues/105

**Comment by wenfangdu** [comment]
@theol0403 Yes, it's a hack, I've converted it to a draft PR to prevent it from merging.

**Comment by Dandarprox** [comment]
@wenfangdu any update on a new non-hacky approach for this functionality? I consider it to be really really necessary. Many extensions and vscode settings don't work properly due to this.  Thanks BTW 😃

**Comment by wenfangdu** [comment]
@Dandarprox Unfortunately, the most reliable way, for now, is still using https://github.com/vscode-neovim/vscode-neovim#invoking-vscode-actions-from-neovim.

**Comment by theol0403** [comment]
Closed in favor of https://github.com/vscode-neovim/vscode-neovim/pull/1258

**Pull request closed without merging**
