### PR TITLE
feat: add options to disable or change selection debounce time

### PR DESCRIPTION
**Pull request by xiyaowong**
new settings

- `vscode-neovim.normalSelectionDebounceTime`
- `vscode-neovim.mouseSelectionDebounceTime`

Resolve: #1475

### CODE REVIEW

**Review by theol0403 — APPROVED** [review]

**Comment by theol0403** [comment]
@xiyaowong out of curiosity, does disabling the mouse also disable cursor move on mouse click? I have a feeling that might still be nice to have even if selections don't enter visual mode.

**Comment by xiyaowong** [comment]
I did a simple test at that time and didn’t find any issues.

**Comment by justinmk** [comment]
To avoid the need for 2 options this could instead be a factor or multiple, like 1x/1.5x/2x/3x. Or from a user's perspective it could be a "dial" or slider, i.e. a range from 1 to 100. Which then would be converted by vscode-neovim to appropriate values internally. No need for users to tweak the exact millisecond values.

**Comment by xiyaowong** [comment]
1. These two options are completely unrelated.

2. At present, I tend to solve the problem now and improve the document later.

3. There is now a limited range of values for these two options.

**Comment by justinmk** [comment]
How are they unrelated? They both control the sync window between client/server. The fact that they control different internals is an implementation detail. When would a user adjust one of these values but not the other?

**Comment by xiyaowong** [comment]
About `normal selection`: #1403, #1409
About `mouse selection`: #1475

The current values range and the candidates are both good. Most users don’t even need to change them, but if they do, they will naturally discover these configuration options. Like VSCode, it has a lot of hidden configurations.

**Pull request merged**
