### PR TITLE
refactor: extends the Custom Disposable

### PR DESCRIPTION
**Pull request by xiyaowong**

### CODE REVIEW

**Comment by justinmk** [comment]
what problem is this solving?

it can be named `Disposable`, there is little risk of conflict. We aren't going to use both at the same time. And imports can be "namespaced" via `import * as foo`

**Comment by xiyaowong** [comment]
Reduce some boilerplate code

**Comment by justinmk** [comment]
there are currently 64 usages of `Disposable` in the project. some of those would be replaced by this new class. And the new class could be namespaced if necessary, e.g. `util.Disposable`. What is the problem?

**Comment by xiyaowong** [comment]
I just thought there could be some improvements here. Now I'm not feeling much improvement.

**Pull request closed without merging**
