### PR TITLE
fix(scrolling): fix c-u/c-y/c-f/c-b by deletion

### LINKED ISSUE #293: Page movements don't affect cursor
`<C-d>`, `<C-u>`, `<C-f>`, and `<C-b>` all move the view but not the cursor, which is inconsistent with native Neovim behavior, which is to move the cursor a half/full screen and only adjust the view if necessary.

### PR DESCRIPTION
**Pull request by theol0403**
# Problem
Window scroll commands don't move the cursor and instead just scroll the window. This differs from nvim behavior. This is because the extension intercepts the keybindings and applies vscode commands instead. The solution from #528 and #855 simply improves the logic in the plugin to move the cursor. However, this adds complexity and increases the separation from nvim.

# Solution
Remove all custom code for cursor scrolling and allow nvim to handle it itself. However, I have found two problems:

- due to `scrolloff=100`, the scrolling commands behave strangely, and don't reach the top of the screen. c-d scrolls twice as far as it should. However, this can't be avoided according to https://github.com/vscode-neovim/vscode-neovim/blob/52ff62612d3bb9ae2a50ce00b9e068c5d175abda/src/main_controller.ts#L55. @justinmk can you think of another solution that will avoid the enforcing of scrolloff? 
https://github.com/vscode-neovim/vscode-neovim/blob/d11c2ed69ab9ab26b82bb6d892443f8ece1fe940/vim/vscode-options.vim#L16
- C-b behaves very strangely, even with scrolloff=0. Sometimes, it moves *down* a line. It never makes it to the top. 

Fixes #293, #580, #528, and #855.

### CODE REVIEW

**Comment by theol0403** [comment]
I found an explanation for why neovim was not originally handling the scrolling. #361

> Yep, unfortunately sending scroll commands from neovim produces jitter (at least it did last time when i've checked). It's possible to restore behaviour by disabling default ctrl+e/ctrl+y bindings and using vscode-neovim.send command instead and notifying back the extension from neovim.

I don't notice any jitter - maybe its safe to use this now?

**Comment by justinmk** [comment]
> // to not deal with screenrow positioning, we set height to high value and scrolloff to value / 2. so screenrow will be always constant 

I'm missing context here, but I wonder if this hack was done before `win_viewport` UI event was available?

**Comment by theol0403** [comment]
> I'm missing context here, but I wonder if this hack was done before `win_viewport` UI event was added to Nvim?

I'm also quite lacking in knowledge, but this seems related to https://github.com/vscode-neovim/vscode-neovim/pull/868#issuecomment-1111619159 . I think the solution to one would be a solution to the other (as well as the solution to many other issues regarding viewport).

**Comment by justinmk** [comment]
If it's possible to remove the hacks while making some small tradeoffs, I'd lean towards that. And then figure out what is needed from Neovim (or VSCode?) to resolve the tradeoffs.

**Comment by theol0403** [comment]
Yeah, I'd say all that we need to merge this is for the `scrolloff` hack to be removed.

**Comment by trkoch** [comment]
I'm having trouble following. Can you bring us up to date what the status of this PR is?

**Comment by theol0403** [comment]
> I'm having trouble following. Can you bring us up to date what the status of this PR is?

Sorry. Here is what happened:

- created this PR to simplify code and not require special PRs
- realised there was fundamental issue with the viewport height and scrolloff being too high, causing the native bindings to not work
-  https://github.com/vscode-neovim/vscode-neovim/pull/919 was merged, which properly syncs viewport height
- I merged this PR
- It turns out that c-u/c-d was still broken, see https://github.com/vscode-neovim/vscode-neovim/pull/993
- Pending https://github.com/vscode-neovim/vscode-neovim/pull/993, I had to revert this PR

So, the current state is "waiting for https://github.com/vscode-neovim/vscode-neovim/pull/993, currently reverted".

**Pull request merged**
