### PR TITLE
feat: add action `start-multiple-cursors`

### PR DESCRIPTION
**Pull request by xiyaowong**
This action can be used to create multiple selections in vscode

refactor: use action for builtin multi-cursor feature

### CODE REVIEW

**Comment by xiyaowong** [comment]
No side effects, merged.

**Comment by trkoch** [comment]
@xiyaowong Can this be used to create multiple cursors while in normal mode? Wouldn’t make sense to associate the default cmd+d keybinding?

**Comment by xiyaowong** [comment]
@trkoch https://github.com/vscode-neovim/vscode-multi-cursor.nvim

**Comment by trkoch** [comment]
@xiyaowong Sounds very promising! I'll take a look. Thank you for your efforts!

**Pull request merged**
