### PR TITLE
feat: support outputting logs to the output channel

### PR DESCRIPTION
**Pull request by QAston**
Add option `vscode-neovim.logOutputToChannel`

### CODE REVIEW

**Comment by theol0403** [comment]
@xiyaowong Investigate using vscode's new logging API. It might provide the ability to log to different places.

**Comment by xiyaowong** [comment]
`TelemetryLogger`? Not feeling well.

**Comment by theol0403** [comment]
I think I'm thinking of LogOutputChannel

**Comment by xiyaowong** [comment]
> I think I'm thinking of LogOutputChannel

This is what was added by this PR. 👀

**Comment by theol0403** [comment]
No, is it not just a regular OutputChannel?

**Comment by theol0403** [comment]
I don't think it is readonly. I haven't looked too much into it, but I'd imagine that the reason it exists is that the vscode devs added some nice formatting for the different log levels. I was maybe hoping to refactor the entire logger to use the vscode logger, or at least parts of it.

**Comment by xiyaowong** [comment]
code

**Comment by theol0403** [comment]
There must be a way to change the log level... or else the API seems useless.

**Comment by xiyaowong** [comment]
> There must be a way to change the log level... or else the API seems useless.

Not possible for now: https://github.com/microsoft/vscode/blob/a8b7239d0311d4915b57c837972baf4b01394491/src/vs/workbench/api/common/extHostOutput.ts#L24

The current project log is sufficient for now. It's just a log, after all.

**Comment by xiyaowong** [comment]
Forgot one crucial fact - we cannot use 'output' because it is a textEditor which would lead to infinite output. @theol0403 🤯

**Pull request closed without merging**
