### PR TITLE
feat(options): synchronize editor line numbers

### LINKED ISSUE #175: :number and :relativenu not working
Hi! Just coming over from the popular Vim extension and so far things are mostly fantastic. However, there seems to be just a couple of quality of life things that would make the package better.

First is possibly tying :nu and :rnu to the line numbers of vscode. I like to change between relative number and number sometimes in the Vim extension, and giving neovim this ability would be great.

The most pressing issue however, is the inability to view :reg, :ju :ls, and other long line outputs, which does work with the popular vim extension. I've seen that the developer is planning to work on this feature, so i'm just putting this out to again express interest :)

Great work guys!

### LINKED ISSUE #1263: Issue Tracker: Sync neovim options
We can connect buffer options according to https://github.com/vscode-neovim/vscode-neovim/pull/656#discussion_r912836951

- [ ] https://github.com/vscode-neovim/vscode-neovim/issues/175

### PR DESCRIPTION
**Pull request by xiyaowong**
Fixes #1263, fixes #175, closes #1340

### CODE REVIEW

**Comment by justinmk** [comment]
The code changes look complicated and fragile, can it be simplified? 

Do the tests correctly fail if you undo the key changes?

**Comment by xiyaowong** [comment]
> The code changes look complicated

Previously, there were many changes due to formatting, and I have reformatted them to reduce unnecessary changes

> fragile

I think it's okay. The key to synchronization is to perceive user changes. Here, we cache the options and make judgments, and artificially construct events

> Do the tests correctly fail if you undo the key changes?

Yes.

**Comment by xiyaowong** [comment]
By default, there will be no side effects unless the user toggle number option. Ready to merge :)

**Comment by theol0403** [comment]
Why closed?

**Comment by xiyaowong** [comment]
Number will break highlights. So we must set &nonumber. Then, there is no way to know changes when user turns off number. 

So there are only two ways:
1. Ask user use a nested autocmd.
2. Ask user use a command like `NumberToggle` we provided.

**Comment by theol0403** [comment]
Yeah, that makes sense. That's what I found out when I made my PR.

**Comment by xiyaowong** [comment]
When I discovered this issue 👇 when I set &number, my heart was broken.
image

**Comment by theol0403** [comment]
I mean... when number is set we could offset highlights. But that is a messy workaround for little gain. Better to improve nvim APIs.

**Comment by xiyaowong** [comment]
> when number is set we could offset highlights

👍

**Comment by xiyaowong** [comment]
Still not working

**Comment by theol0403** [comment]
Tests failing I believe.

**Comment by xiyaowong** [comment]
Fixed :)

**Review by theol0403 — APPROVED** [review]

**Pull request merged**
