### PR TITLE
feat(options): synchronize editor line number style

### PR DESCRIPTION
**Pull request by theol0403**
Fixes https://github.com/vscode-neovim/vscode-neovim/issues/1263, fixes https://github.com/vscode-neovim/vscode-neovim/issues/175, supersedes https://github.com/vscode-neovim/vscode-neovim/pull/656.

For now, this PR just syncs number/relative number, but lays the groundwork for syncing more options. This allows for smart relative numbers (https://github.com/jeffkreeftmeijer/vim-numbertoggle).

However, that specific plugin does not work, because it first checks if `nu` is set, but we force it to be off. 

A working snippet is 

```vim
augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if mode() != "i" | set rnu   | endif
  autocmd BufLeave,FocusLost,InsertEnter,WinLeave   * if &nu           | set nornu | endif
augroup END
```

### CODE REVIEW

**Comment by theol0403** [comment]
Actually, this does not seem to work. It seems setting inside the `InsertLeave`/`InsertEnter` autocommand skips `OptionSet`.

**Comment by justinmk** [comment]
> It seems setting inside the `InsertLeave`/`InsertEnter` autocommand skips `OptionSet`.

That is intentional; you can opt-in to recursion by using `++nested` (`:help autocmd-nested`).

But that means any users or nvim plugins that are creating things like your `augroup numbertoggle` example must specify `++nested` on their autocmd definitions.

There is also the `option_set` UI event (`:help ui-global`) which is emitted on the RPC channel, but it only covers certain options.

**Comment by theol0403** [comment]
Yeah, that doesn't include number. I'm not sure if there is any way of doing this then.

**Comment by justinmk** [comment]
The approach here addresses #175 , no? It sounds like people just want to do `:set nu` from a mapping or the cmdline, neither of which is a nested autocmd.

**Pull request closed without merging**
