### PR TITLE
README: added conditional init.lua

### PR DESCRIPTION
**Pull request by Lyr-7D1h**

### CODE REVIEW

**Review by tobealive — APPROVED** [review]
Why not `vim.g.vscode ~= 0`?

Additionally, I would check for equality with 1 instead of inequality with 0 here. 
When I'm still getting it right, I think the reason why I learned to prefer this is that I ran into occasions where such variable checks returned a boolean and an unequal  0 didn't get hooked. But I might confuse something here and changing the equality check won't make a difference, no matter the scenario.

**Review by tobealive — COMMENTED** [review]
Why not using vim.g.vscode ~= 0 😊?

**Comment by theol0403** [comment]
Yes, when I got to this I was going to suggest `if vim.g.vscode then`.

I was also planning on giving some tips on conditional loading with packer.nvim.

**Comment by Lyr-7D1h** [comment]
@theol0403 yes definitely cleaner. I updated the docs!

**Review by theol0403 — APPROVED** [review]

**Comment by theol0403** [comment]
Thank you for the PR!

**Pull request merged**
