### PR TITLE
bug: Add configuration to skip syncing extension visible windows

### PR DESCRIPTION
**Pull request by andrewDoing**
Issue: https://github.com/vscode-neovim/vscode-neovim/issues/2184

This code change fixes the issue at the cost of being able to navigate the generated code windows in Copilot Chat. There is probably a more ideal solution where these windows are handled/synced with neovim in a faster way, but in my experience, I don't navigate these with vim anyway, and I'd rather have the neovim instance functioning.

### CODE REVIEW

**Comment by xiyaowong** [comment]
This is not the solution. What we need to solve is why there will be problems when there are many editors.

**Comment by andrewDoing** [comment]
I understand that there's a better solution, but what if I add a configuration field like "disableCopilotChat" that toggles this behavior? Once the performance of many windows is solved (maybe by me but probably by someone else) this code is easily findable and deletable.

**Comment by xiyaowong** [comment]
I don't think there are performance issues here, whether it's the code blocks in Copilot chat or the large Git diffs; we've tested them before.

**Comment by justinmk** [comment]
https://github.com/vscode-neovim/vscode-neovim/issues/2267#issuecomment-2381694486 may be a good place to start. It looks like we have an `OptionSet` handler that can trigger an infinite loop.

**Comment by xiyaowong** [comment]
The editors were originally no different, but treating them separately would only increase the maintenance burden.

**Pull request closed without merging**
