### PR TITLE
fix(typing_manager): Optimize Non-English input method cause replace previous chars

### LINKED ISSUE #984: Duplicated insertion while typing korean
It seems something wrong in typing korean after update 0.0.89.

녹화_2022_08_02_05_18_23_575

But when I downgraded vscode-neovim 0.0.88, it doesn't happen and everything works fine.

녹화_2022_08_02_05_21_53_807

Version: 1.69.2 (user setup)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:52.460Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

### LINKED ISSUE #989: [BUG] v0.0.89 causes flickering IME input
This is the type of problem that causes me to migrate from VSCodeVim to vscode-neovim, but now vscode-neovim has it too, please fix this, I will stick with v0.0.88 for now.

v0.0.88

STG 2022-08-02 15_31_02

v0.0.89

STG 2022-08-02 15_33_42

Notice in v0.0.89 the background IME text flickers all the time.

Seems to be caused by https://github.com/vscode-neovim/vscode-neovim/pull/900.

### PR DESCRIPTION
**Pull request by BTBMan**
Optimize this [pr](https://github.com/vscode-neovim/vscode-neovim/pull/900)

Also fix #984, fix #989

## Solution

Only register `replacePreviousChar` command when not in insert mode and dispose in insert mode.

And also register `compositionStart` and `compositionEnd` commands to listening text composition and then mark it.

And then send text to nvim client when composition end.

I think It's also fix #984 and fix #989 if it works correctly. because it's not register `replacePreviousChar` in insert mode.

### CODE REVIEW

**Comment by theol0403** [comment]
Thank you for the PR! Can you check if the changes I made still work? If so I'll merge. 

Please test: @wenfangdu @zuhanit @74th @snaka @vlwkaos

[vscode-neovim-replaceprevchar.zip](https://github.com/vscode-neovim/vscode-neovim/files/9384302/vscode-neovim-replaceprevchar.zip)

Rename `.zip` to `.vsix`. Note: this also contains some WIP scrolling PRs that got merged to master but won't be released yet.

**Comment by snaka** [comment]
@theol0403 @BTBMan 
Unfortunately, it was not working correctly in my environment.

https://user-images.githubusercontent.com/19329/185721913-d47b5d3d-f627-4467-8162-492b00f868a2.mp4

**Comment by wenfangdu** [comment]
Me neither, I appreciate the work, but it's worse than #989, the input isn't only flickery, and also trimed:

STG 2022-08-20 10_24_20

**Comment by vlwkaos** [comment]
I tested 0.9.0, typing Korean works OK.

I think the difference Is because the composition of Chinese or Japanese characters works differently from composition of Korean characters. 

As far as I know the former creates a placeholder position(input) for a specific character to be composed by typing--for example roman alphabet--before it actually becomes an input, the latter inputs character as it composes. Maybe this information will help?...

**Comment by BTBMan** [comment]
@snaka @wenfangdu Have you tried it to reload window or restart VSCode? Is it still not working correctly after that?

**Comment by wenfangdu** [comment]
@BTBMan Nope, neither with Sougou Pinyin or Microsoft Pinyin.

**Comment by BTBMan** [comment]
@wenfangdu Maybe you can try to reload VSCode window or restart VSCode before test, I'm using Rime on Mac. And I tried to use built-in IME and still working. 😢

**Comment by wenfangdu** [comment]
@BTBMan I tried reloading multiple times before testing.

**Comment by BTBMan** [comment]
@wenfangdu Headache 😖.

**Comment by wenfangdu** [comment]
@BTBMan The built-in IME (简体拼音) on mac doesn't work either:

https://user-images.githubusercontent.com/28700378/185858087-ddcc00fe-70a3-4464-a09d-3d483d6bf800.mp4

**Comment by wenfangdu** [comment]
> Thank you for the PR! Can you check if the changes I made still work? If so I'll merge.
> 
> Please test: @wenfangdu @zuhanit @74th @snaka @vlwkaos
> 
> [vscode-neovim-replaceprevchar.zip](https://github.com/vscode-neovim/vscode-neovim/files/9384302/vscode-neovim-replaceprevchar.zip)
> 
> Rename `.zip` to `.vsix`. Note: this also contains some WIP scrolling PRs that got merged to master but won't be released yet.

@BTBMan Can you reproduce using this VSIX file?

**Comment by BTBMan** [comment]
@vlwkaos Maybe, But the interesting thing is it will not listening `replacePrevChar` in insert mode, that is correct. but it's not.

**Comment by BTBMan** [comment]
@wenfangdu Whoops. It's not working correctly sometimes... and sometimes. it's working correctly .

**Comment by BTBMan** [comment]
[vscode-neovim-replaceprevchar.zip](https://github.com/vscode-neovim/vscode-neovim/files/9392200/vscode-neovim-replaceprevchar.zip)

 @wenfangdu @zuhanit @74th @snaka @vlwkaos

try to use this test, thanks.

**Comment by wenfangdu** [comment]
> [vscode-neovim-replaceprevchar.zip](https://github.com/vscode-neovim/vscode-neovim/files/9392200/vscode-neovim-replaceprevchar.zip)
> 
> @wenfangdu @zuhanit @74th @snaka @vlwkaos
> 
> try to use this for test, thanks.

@BTBMan This one seems normal.

STG 2022-08-22 15_59_22

**Comment by BTBMan** [comment]
@wenfangdu Waiting for the test results of other people quietly. 😁

**Comment by zuhanit** [comment]
Sorry, I'm late. 😥 It works for me.
녹화_2022_08_23_06_50_46_976

**Comment by BTBMan** [comment]
Great!

**Comment by snaka** [comment]
@BTBMan 
It looks like OK 👍 
Thanks!

https://user-images.githubusercontent.com/19329/186179719-c2c5f933-c029-45a1-9830-845556a23d61.mp4

**Review by theol0403 — APPROVED** [review]

**Comment by xlboy** [comment]
Hey, Thank you very much for making this contribution!

However, There are some new situations on my side. When using the `4-key select first item` feature of `Rime` input method, There will be the problem of text loss. 🥺

---

 ↓ Examples of error:

https://user-images.githubusercontent.com/63690944/189414039-3da99bfd-5f43-4aa1-845c-54cc3c9385d6.mov

 ↓ Examples of normal:

https://user-images.githubusercontent.com/63690944/189414264-0cf510d4-d5c2-40cb-aabe-b2a42dc90de2.mov

 ---

When I press `zdup` key, The focus should print `自动上屏`. But it is currently processed as `z自动上`.

**Comment by BTBMan** [comment]
> [vscode-neovim-replaceprevchar.zip](https://github.com/vscode-neovim/vscode-neovim/files/9392200/vscode-neovim-replaceprevchar.zip)
> 
> @xlboy 
> 
> Is there a problem if you try to use this for the test?

**Comment by xlboy** [comment]
> [vscode-neovim-replaceprevchar.zip](https://github.com/vscode-neovim/vscode-neovim/files/9392200/vscode-neovim-replaceprevchar.zip)
> 
> @xlboy
> 
> Is there a problem if you try to use this for the test?

After testing, it is found that it perfectly solves the problem I described. Thank you!

**Pull request merged**
