### PR TITLE
set neovim working directory on every buffer load

### LINKED ISSUE #2058: bug: Working directory not set correctly with WSL installation (again)
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Windows 11 w/ WSL (Ubuntu)

### Describe the bug

Getting the current working directory doesn't work when running with WSL.  !pwd gives the vscode installation directory, and so :e, :sp, :w, etc all don't work properly, nor do their tab completions.

There was an existing #520 but it has returned, because the fix in PR #1689 is no longer valid due to multi-root workspaces, etc.  Now the workspace directory is only valid in the context of a particular file.

Therefore, the working directory needs to be set upon every buffer change, instead of just once when running neovim.

I tested this approach and it seems to work.  I'll submit the PR later today.

### Steps To Reproduce

1. Install neovim within WSL, and set up the extension to use it
2. Within a WSL terminal in a project directory, run `code .`
3. open one of the files
4. hit :!pwd

### Expected Behavior

EXPECTED: project directory shows
ACTUAL: vscode installation path shows

### PR DESCRIPTION
**Pull request by captaincaius**
Resolve #2058

### CODE REVIEW

**Review by xiyaowong — CHANGES_REQUESTED** [review]
- It is necessary to perform checks to avoid redundant calls.
- Ensure it works correctly during remote development.
- Can we remove this?:
https://github.com/vscode-neovim/vscode-neovim/blob/927ed955d9075f40bb5f2f40d2ad9e057f13906c/src/main_controller.ts#L209-L213

**Comment by xiyaowong** [comment]
Also, can we remove this?

https://github.com/vscode-neovim/vscode-neovim/blob/927ed955d9075f40bb5f2f40d2ad9e057f13906c/src/main_controller.ts#L209-L213

**Comment by ollien** [comment]
> It is necessary to perform checks to avoid redundant calls.

Why? Isn't the worst case we change the PWD to a directory we're already in, which is a no-op?

**Comment by xiyaowong** [comment]
Alright, Vim has already checked it.

https://github.com/neovim/neovim/blob/3a1515bfee59710b4da9bfdf0fc4ecb5b13a00db/src/nvim/ex_docmd.c#L5789-L5790

**Comment by captaincaius** [comment]
> * ~It is necessary to perform checks to avoid redundant calls.~
> * Ensure it works correctly during remote development.
> * Can we remove this?:
>   https://github.com/vscode-neovim/vscode-neovim/blob/927ed955d9075f40bb5f2f40d2ad9e057f13906c/src/main_controller.ts#L209-L213

Yeah I think you're right - it's probably not needed anymore.  I didn't try it though - I wasn't sure you folks would want it in the same PR or a future cleanup issue.

Since I need to reroll for the lint stuff anyway, I might as well add it.  Clean commit and PR coming.

**Pull request closed without merging**
