### PR TITLE
fix(typing_manager): Non-English input method can replace chars

### PR DESCRIPTION
**Pull request by BTBMan**
Fix bug #560

## Problem

It can replace previous chars when type Non-English chars without insert mode. It's very annoying.

## Solution

I register `replacePreviousChar` command to handle this behavior

It can stop replace previous chars without insert mode

### CODE REVIEW

**Comment by BTBMan** [comment]
@asvetliakov 🙏 Hope to merge this. Thanks!

**Comment by theol0403** [comment]
I don't understand what this is supposed to do. Can you please explain the problem and how this solves it?

**Comment by BTBMan** [comment]
Current:

bad

Optimized:

good

It can replace previous chars before optimized, I reference [VSCodeVim](https://github.com/VSCodeVim/Vim/blob/fe9b77de6de3ab73ff2f9a1eeee7c94ea159a771/extensionBase.ts#L365).

But I realized It also has some bugs, It can also replace chars sometimes and It cause Non-English text blink.

**Comment by BTBMan** [comment]
VSCodeVim also has text blink problem, I don't know whether it is VScode problem, It don't had that problem when I use VSCodeVim long time ago.

**Comment by theol0403** [comment]
> VSCodeVim also has text blink problem, I don't know whether it is VScode problem, It don't had that problem when I use VSCodeVim long time ago.

Can you give a link for where they talk about this?

Can you try adding to settings:
```js
  "extensions.experimental.affinity": {
    "vscodevim.vim": 1,
    "asvetliakov.vscode-neovim": 1
  },
```

**Comment by BTBMan** [comment]
Sorry, I don't have, I have given up using VSCodeVim to use VSCodeNeovim for a long time, I just found that this extension has some bad experience, So I refer to the idea in VSCodeVim and use it.

**Comment by BTBMan** [comment]
I just found a issues about this in VSCodeVim.
[https://github.com/VSCodeVim/Vim/issues/341](https://github.com/VSCodeVim/Vim/issues/341)

**Comment by BTBMan** [comment]
It seems that text jitter is indeed a problem of VSCodeVim

**Comment by theol0403** [comment]
Is it possible to instead use https://github.com/microsoft/vscode/issues/8133#issuecomment-232958381 instead of `replacePreviousChar`? I am just worried about side effects.

**Comment by BTBMan** [comment]
I tried, I think It's useless, Now only `replacePreviousChar` can fix it.

**Review by theol0403 — APPROVED** [review]

**Comment by wenfangdu** [comment]
I think this PR should be reverted, compared to the jittering IME input, the return is negligible.

@BTBMan Dude, I saw your comment [here](https://github.com/VSCodeVim/Vim/issues/7496#issuecomment-1181803905), if that's true, then we should wait for `replacePreviousChar` to be fixed before merging this.

**Comment by BTBMan** [comment]
@theol0403 I think it's a solution. What did you think?

**Comment by theol0403** [comment]
Sure, I'll revert and please let me know when I can merge, if #984 is also fixed.

**Comment by BTBMan** [comment]
Ok!

**Pull request merged**
