### PR TITLE
fix(blockwise-visual): handle double-width chars and tabs

### PR DESCRIPTION
**Pull request by xiyaowong**
improvement: the selection direction is consistent with nvim

Issue - Fixed

### CODE REVIEW

**Comment by trkoch** [comment]
@xiyaowong Not sure I can follow the GIF. The issue you're fixing is that some characters are not selected which should?

**Comment by theol0403** [comment]
Isn't there a built in vim function to convert display col to col? Could this PR not be simplified to just converting the column before sending it to VS code? This code seems a little complex.

**Comment by xiyaowong** [comment]
> Isn't there a built in vim function to convert display col to col? 

Oh! I forgot to search for the built-in function. There is `virtcol2col`

**Comment by xiyaowong** [comment]
@theol0403 Not sure if `virtcol2col` can simplify the code, after all, we still need to convert byte-index to char-index. And this function depends on a window

**Comment by theol0403** [comment]
Isn't there also a function to convert char to byte char?

**Comment by xiyaowong** [comment]
vim.str_utfindex

I'll refactor it when I have time. But, using multiple built-in functions is not necessarily more concise.

**Comment by theol0403** [comment]
What about https://neovim.io/doc/user/builtin.html#charidx()

**Comment by xiyaowong** [comment]
It seems almost the same

vim.str_utfindex is widely used in nvim-lsp. Maybe it's better?. I'm not sure. I haven't used any of these functions.

**Pull request merged**
