### PR TITLE
Fix cursor jumps when switching split-screen tabs

### PR DESCRIPTION
**Pull request by mussinbenarbia**
Fixes https://github.com/vscode-neovim/vscode-neovim/issues/776

Took a stab at this since I've had this happen to me as well a couple of times.
I did some tests with multiple files and tabs and it seems to work fine but I would appreciate it if someone else tried it as well 🙏  

https://user-images.githubusercontent.com/77260898/150796674-3651c6fa-5d2e-48ef-8212-818c235971c5.mov

It's my first time contributing to this amazing project so pardon me if I did something wrong. Please let me know if there is anything else that I can do for this PR.

### CODE REVIEW

**Comment by QAston** [comment]
I've had a similar issue and solved it with https://github.com/vscode-neovim/vscode-neovim/pull/716, do you still have the issue if you apply that instead? It block sending positions from insert mode which was what was causing the issue I believe.

**Comment by mussinbenarbia** [comment]
I tried running the extension off of the `feature/insert-mode-by-default` branch but it seems the issue is not resolved. Just making sure I did it correctly, I wiped `dist` and re-ran the extension while checking out your branch and this is the behavior of the cursor when jumping between tabs while in insert mode, same as in `master`:

https://user-images.githubusercontent.com/77260898/154809750-ddb7e26a-6d04-4163-8bbf-1e255a902798.mov

**Comment by QAston** [comment]
Cool, looks like both patches are needed then, thanks

**Comment by trkoch** [comment]
I checked this out. Seems to work fine.

**Comment by Jakoviz** [comment]
> I checked this out. Seems to work fine.

Would you approve this? Hoping to get this fix soon.

**Review by Jakoviz — APPROVED** [review]
Works for me.

**Review by theol0403 — APPROVED** [review]

**Comment by trkoch** [comment]
> I've had a similar issue and solved it with https://github.com/vscode-neovim/vscode-neovim/pull/716

For the record, reverting #808 and applying #716 I end up with the original issue (jumps) fixed and correct cursor position after leaving insert mode (no regression). We should probably decompose #716. It does many things in just one commit, but the original author seems to have lost interest.

**Comment by theol0403** [comment]
Actually, this caused a regression.

Reproduce by opening an empty file and typing `abc<Esc>`. The cursor jumps to the beginning of the line, instead of staying at the end. Then, type `A12<CR>3<Esc>`. The cursor jumps to the middle of the first line instead of staying on the `3` in the bottom line.

**Comment by theol0403** [comment]
Please repoen this in a new issue and we can investigate the cause or find another solve for #776

**Pull request merged**
