### PR TITLE
fix: update default debounce time for selection to 100

### LINKED ISSUE #1752: [Bug] `ci'`, cursor jumps to the end of line
OS: macOS 14
nvim: 0.9.5
vscode-nvim: 1.5.0

vscode-neovim behavior (cursor jumps to the end of the line):

https://github.com/vscode-neovim/vscode-neovim/assets/28700378/238e82cd-8bfc-4e7b-a25d-1cc9b2758bde

Neovim behavior (cursor stays inside the quotes):

https://github.com/vscode-neovim/vscode-neovim/assets/28700378/b71d0191-ddeb-4c1e-8063-e4bf10b39f83

Code:

```styl
$base = '../rewards'
$bgi = $proxy($base, 'bgi')

@import '../includes/highlight.styl'

.open-task-btn
  $bgi '../static/rewards/open-tasks-btn-double.png'
  $highlight '../static/rewards/open-tasks-btn-double.png'
```

### PR DESCRIPTION
**Pull request by wenfangdu**
fix #1752

### CODE REVIEW

**Comment by wenfangdu** [comment]
@xiyaowong Why did you close it?

**Comment by wenfangdu** [comment]
@xiyaowong What are the other issues it might cause, the difference is only 50ms, dude. Even if there're side effects, the tradeoff is still worth it, better than having to wait for months and years to understand why. Of course, it fixed, the PR description stated it fixed #1752.

**Comment by wenfangdu** [comment]
Smaller debounce time increases chances of race conditions and other performance issues, besides, `100` is used as the default value for `vscode-neovim.mouseSelectionDebounceTime` too. @xiyaowong

**Comment by xiyaowong** [comment]
#1403

**Comment by wenfangdu** [comment]
@xiyaowong It's not the same thing, `vscode-neovim.normalSelectionDebounceTime` is strictly for selections.
image

**Comment by xiyaowong** [comment]
Some users call `cursorMove` to move the cursor, any delay in synchronizing the cursor position will affect other operations (e.g., c, d, x, a, i, etc). As for why the debounce time for mouse selection is longer, it's because mouse selection triggers events more frequently, and using the mouse typically doesn't involve rapid editing operations.

**Comment by wenfangdu** [comment]
@xiyaowong Whatever, man, just make sure to mention this bug in the doc, in case someone stepped into this trap.

**Comment by wenfangdu** [comment]
@xiyaowong Whatever, man, just make sure to mention this bug in the doc, in case someone stepped into this trap, took ages to debug.

**Pull request closed without merging**
