### PR TITLE
Folding support

### LINKED ISSUE #58: Folding
Need to sync vscode folds to neovim. from the initial look ```onDidChangeTextEditorVisibleRanges``` could be used with ```:{range}fold``` command
Rebind neovim folding keys/commands to call vscode folds commands

### PR DESCRIPTION
**Pull request by asvetliakov**
Fixes #58 

Seems easy to add basic support. By design vscode folds must be used, and neovim won't be aware of them. However we'll skip fold block when moving line-by-line in vscode. 

The fold will be opened automatically if you perform `<num>j/k` where `num > 1` and the target line is within a fold

- [x] Movement over folds
- [ ] Commands/Mappings
- [ ] Tests

### CODE REVIEW

**Comment by trkoch** [comment]
I'd really love to see this merged!

**Comment by tejasvi** [comment]
I use these mappings.
```
nnoremap <silent> za <Cmd>call VSCodeNotify('editor.toggleFold')<CR>
nnoremap <silent> zR <Cmd>call VSCodeNotify('editor.unfoldAll')<CR>
nnoremap <silent> zM <Cmd>call VSCodeNotify('editor.foldAll')<CR>
nnoremap <silent> zo <Cmd>call VSCodeNotify('editor.unfold')<CR>
nnoremap <silent> zO <Cmd>call VSCodeNotify('editor.unfoldRecursively')<CR>
nnoremap <silent> zc <Cmd>call VSCodeNotify('editor.fold')<CR>
nnoremap <silent> zC <Cmd>call VSCodeNotify('editor.foldRecursively')<CR>

nnoremap <silent> z1 <Cmd>call VSCodeNotify('editor.foldLevel1')<CR>
nnoremap <silent> z2 <Cmd>call VSCodeNotify('editor.foldLevel2')<CR>
nnoremap <silent> z3 <Cmd>call VSCodeNotify('editor.foldLevel3')<CR>
nnoremap <silent> z4 <Cmd>call VSCodeNotify('editor.foldLevel4')<CR>
nnoremap <silent> z5 <Cmd>call VSCodeNotify('editor.foldLevel5')<CR>
nnoremap <silent> z6 <Cmd>call VSCodeNotify('editor.foldLevel6')<CR>
nnoremap <silent> z7 <Cmd>call VSCodeNotify('editor.foldLevel7')<CR>

nnoremap <silent> zV <Cmd>call VSCodeNotify('editor.foldAllExcept')<CR>
```
`zV` is analogue of `zv`.

**Comment by trkoch** [comment]
I noticed moving with `[` and `(` unfolds. Could we extend skipping to certain movements? It probably doesn't make much sense to include `/` (search) – if it even feasible.

**Comment by srustamo** [comment]
@tejasvi where do you put these mappings? VSCodium, vimrc, elsewere?

**Comment by tejasvi** [comment]
@srustamo In `init.vim`. Check `:echo $MYVIMRC` for exact path.

**Review by throwaway69420-69420 — APPROVED** [review]

**Comment by throwaway69420-69420** [comment]
any idea when this will be merged? @asvetliakov

**Review by BTBMan — COMMENTED** [review]
It's exactly resolve some problem

**Comment by trkoch** [comment]
@theol0403 I've been using this for a while now and, while limited, it works fine.

Before merging this, I suggest we add the mappings [mentioned](https://github.com/vscode-neovim/vscode-neovim/pull/502#issuecomment-831682643) above and write a simple test where we skip over a fold. More features can be implemented in a follow-up PR.

**Comment by jsonMartin** [comment]
> nnoremap <silent> za <Cmd>call VSCodeNotify('editor.toggleFold')<CR>
> nnoremap <silent> zR <Cmd>call VSCodeNotify('editor.unfoldAll')<CR>
> nnoremap <silent> zM <Cmd>call VSCodeNotify('editor.foldAll')<CR>
> nnoremap <silent> zo <Cmd>call VSCodeNotify('editor.unfold')<CR>
> nnoremap <silent> zO <Cmd>call VSCodeNotify('editor.unfoldRecursively')<CR>
> nnoremap <silent> zc <Cmd>call VSCodeNotify('editor.fold')<CR>
> nnoremap <silent> zC <Cmd>call VSCodeNotify('editor.foldRecursively')<CR>
> 
> nnoremap <silent> z1 <Cmd>call VSCodeNotify('editor.foldLevel1')<CR>
> nnoremap <silent> z2 <Cmd>call VSCodeNotify('editor.foldLevel2')<CR>
> nnoremap <silent> z3 <Cmd>call VSCodeNotify('editor.foldLevel3')<CR>
> nnoremap <silent> z4 <Cmd>call VSCodeNotify('editor.foldLevel4')<CR>
> nnoremap <silent> z5 <Cmd>call VSCodeNotify('editor.foldLevel5')<CR>
> nnoremap <silent> z6 <Cmd>call VSCodeNotify('editor.foldLevel6')<CR>
> nnoremap <silent> z7 <Cmd>call VSCodeNotify('editor.foldLevel7')<CR>
> 
> xnoremap <silent> zV <Cmd>call VSCodeNotify('editor.foldAllExcept')<CR>

Thanks for this, I was wondering how to make code folding work in VS Code.

I added to my `init.vim` file , under a if check:
```
if exists('g:vscode')
	xmap gc  <Plug>VSCodeCommentary
	nmap gc  <Plug>VSCodeCommentary
	omap gc  <Plug>VSCodeCommentary
	nmap gcc <Plug>VSCodeCommentaryLine

	nnoremap <silent> za <Cmd>call VSCodeNotify('editor.toggleFold')<CR>
	nnoremap <silent> zR <Cmd>call VSCodeNotify('editor.unfoldAll')<CR>
	nnoremap <silent> zM <Cmd>call VSCodeNotify('editor.foldAll')<CR>
	nnoremap <silent> zo <Cmd>call VSCodeNotify('editor.unfold')<CR>
	nnoremap <silent> zO <Cmd>call VSCodeNotify('editor.unfoldRecursively')<CR>
	nnoremap <silent> zc <Cmd>call VSCodeNotify('editor.fold')<CR>
	nnoremap <silent> zC <Cmd>call VSCodeNotify('editor.foldRecursively')<CR>

	nnoremap <silent> z1 <Cmd>call VSCodeNotify('editor.foldLevel1')<CR>
	nnoremap <silent> z2 <Cmd>call VSCodeNotify('editor.foldLevel2')<CR>
	nnoremap <silent> z3 <Cmd>call VSCodeNotify('editor.foldLevel3')<CR>
	nnoremap <silent> z4 <Cmd>call VSCodeNotify('editor.foldLevel4')<CR>
	nnoremap <silent> z5 <Cmd>call VSCodeNotify('editor.foldLevel5')<CR>
	nnoremap <silent> z6 <Cmd>call VSCodeNotify('editor.foldLevel6')<CR>
	nnoremap <silent> z7 <Cmd>call VSCodeNotify('editor.foldLevel7')<CR>

	xnoremap <silent> zV <Cmd>call VSCodeNotify('editor.foldAllExcept')<CR>
endif
```

Would love to see this implemented natively though by the Plugin!

**Comment by xlboy** [comment]
I hope it can be used. 🙃

**Comment by xlboy** [comment]
When using `folding feature`, If i use the command `workbench.action.gotoLine` to move the cursor to the folding line, the movement will fail.

**Comment by meicale** [comment]
Looks like it doesn't work and everyone has alternatives? Folding the code is needed when explore code base.

**Comment by nmsobri** [comment]
what the status on this? really need this feature to navigate big codebase.. somehow, when moving through fold with `j` or `k` it will unfold.. truly annoying.. hope to see this feature get more love

**Comment by lfire** [comment]
@asvetliakov Why does this function keep getting blocked?

**Comment by justinmk** [comment]
This is quite out of date with the current codebase.

**Comment by accrrsd** [comment]
> I use these mappings.
> 
> ```
> nnoremap <silent> za <Cmd>call VSCodeNotify('editor.toggleFold')<CR>
> nnoremap <silent> zR <Cmd>call VSCodeNotify('editor.unfoldAll')<CR>
> nnoremap <silent> zM <Cmd>call VSCodeNotify('editor.foldAll')<CR>
> nnoremap <silent> zo <Cmd>call VSCodeNotify('editor.unfold')<CR>
> nnoremap <silent> zO <Cmd>call VSCodeNotify('editor.unfoldRecursively')<CR>
> nnoremap <silent> zc <Cmd>call VSCodeNotify('editor.fold')<CR>
> nnoremap <silent> zC <Cmd>call VSCodeNotify('editor.foldRecursively')<CR>
> 
> nnoremap <silent> z1 <Cmd>call VSCodeNotify('editor.foldLevel1')<CR>
> nnoremap <silent> z2 <Cmd>call VSCodeNotify('editor.foldLevel2')<CR>
> nnoremap <silent> z3 <Cmd>call VSCodeNotify('editor.foldLevel3')<CR>
> nnoremap <silent> z4 <Cmd>call VSCodeNotify('editor.foldLevel4')<CR>
> nnoremap <silent> z5 <Cmd>call VSCodeNotify('editor.foldLevel5')<CR>
> nnoremap <silent> z6 <Cmd>call VSCodeNotify('editor.foldLevel6')<CR>
> nnoremap <silent> z7 <Cmd>call VSCodeNotify('editor.foldLevel7')<CR>
> 
> xnoremap <silent> zV <Cmd>call VSCodeNotify('editor.foldAllExcept')<CR>
> ```
> 
> `zV` is analogue of `zv`.

For those who use init.lua, it looks like:
vim.keymap.set("n", "zc", "<cmd>lua require('vscode').action('editor.fold')<CR>")
vim.keymap.set("n", "za", "<cmd>lua require('vscode').action('editor.toggleFold')<CR>")
vim.keymap.set("n", "zR", "<cmd>lua require('vscode').action('editor.unfoldAll')<CR>")
vim.keymap.set("n", "zM", "<cmd>lua require('vscode').action('editor.foldAll')<CR>")
vim.keymap.set("n", "zo", "<cmd>lua require('vscode').action('editor.unfold')<CR>")
vim.keymap.set("n", "zO", "<cmd>lua require('vscode').action('editor.unfoldRecursively')<CR>")
vim.keymap.set("n", "zc", "<cmd>lua require('vscode').action('editor.fold')<CR>")
vim.keymap.set("n", "zC", "<cmd>lua require('vscode').action('editor.foldRecursively')<CR>")

**Pull request closed without merging**
