### PR TITLE
fix(map): move wrapped lines in visual mode with gk/gj

### PR DESCRIPTION
**Pull request by ctstacey**
Add mapping to move up/down virtual lines (i.e. wrapped lines), in visual modes.

Complements the current mapping for moving up/down virtual lines in normal mode.

### CODE REVIEW

**Comment by theol0403** [comment]
Does this still encounter the issues present in https://github.com/vscode-neovim/vscode-neovim/issues/576?

**Comment by theol0403** [comment]
This might work now with the new visual selection PR, will give it a try.

**Comment by theol0403** [comment]
Actually, now it definitely does not work, because vscode does not know where the actual (fake) cursor is.

**Comment by xiyaowong** [comment]
From the current perspective, implementing this feature requires continuously saving the cursor positions in both the editor and Neovim, and then performing a series of checks during the bidirectional synchronization process. However, moving by `wrappedLine` in visual mode is a trivial functionality.

**Pull request closed without merging**
