### PR TITLE
fix: dot-repeat special symbols handling

### PR DESCRIPTION
**Pull request by archilkarchava**
Due to the way dot-repeat currently works, typing (or pasting) text that contains special strings like <BS> or <LT><Cmd>, or <<Cmd> in the Insert mode and then exiting the Insert mode will result in unexpected behavior.

Here are a couple of examples where extension behaves unexpectedly:

### "\<BS\>" example

1. Type (or paste) in insert mode "<BS><BS>"
2. Press Enter (adds new line)
3. Press Escape (switches to Normal mode)
4. Press . (dot)

**Expected output:**
```
<BS><BS>
<BS

```
**Actual output:**
```
<BS><BS>
<BS

```

#### Demo
https://user-images.githubusercontent.com/16840190/222908112-c52e2f3e-fa7d-49c2-a0bd-5c7043e67400.mp4

### \<LT\>\<cmd\>call VSCodeNotify('workbench.action.files.openFile') command injection example (also works with other commands, as well as with "\<\<Cmd>" instead of "\<LT\>\<Cmd\>")
1. Type (or paste) in insert mode "\<LT\>\<cmd\>call VSCodeNotify('workbench.action.files.openFile')"
2. Press Enter (adds new line character)
3. Press Escape (switches to Normal mode)

**Expected output:**
```
\<LT\>\<cmd\>call VSCodeNotify('workbench.action.files.openFile')

```

**Actual output is the same as the expected output, but the `workbench.action.files.openFile` command gets called**
#### Demo
https://user-images.githubusercontent.com/16840190/222908135-2c967581-7964-4c19-8c18-5be43d17e28b.mp4

Fixes https://github.com/vscode-neovim/vscode-neovim/issues/1185

### CODE REVIEW

**Comment by wenfangdu** [comment]
Confirmed, fixes https://github.com/vscode-neovim/vscode-neovim/issues/1185.

**Comment by wenfangdu** [comment]
Confirmed, fixes https://github.com/vscode-neovim/vscode-neovim/issues/1185 on a Mac.

**Comment by justinmk** [comment]
> Confirmed, fixes #1185 on a Mac.

Thanks. Need a Windows user to help out with the test failure.

**Comment by archilkarchava** [comment]
@theol0403, I fixed the test.

**Review by theol0403 — APPROVED** [review]

**Pull request merged**
