### PR TITLE
chore(master): release 1.11.5

### PR DESCRIPTION
**Pull request by theol0403**
:robot: I have created a release *beep* *boop*
---

### Bug Fixes

* **eval:** try serializing the object result ([#1966](https://github.com/vscode-neovim/vscode-neovim/issues/1966)) ([b387d29](https://github.com/vscode-neovim/vscode-neovim/commit/b387d29568ca7976851fa7a1b485e204b7d34b08))
* **incsearch:** win cursor not properly revealed ([#1971](https://github.com/vscode-neovim/vscode-neovim/issues/1971)) ([116abdd](https://github.com/vscode-neovim/vscode-neovim/commit/116abddcb70a2daccf6fd9e29b51b08724c3141c))
* reduce text jumpiness when using the substitute command ([#1973](https://github.com/vscode-neovim/vscode-neovim/issues/1973)) ([d6e44dd](https://github.com/vscode-neovim/vscode-neovim/commit/d6e44dda9d46463879ae5733ee157dbae3c90a23))

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Comment by xiyaowong** [comment]
Don't release it yet

**Comment by ollien** [comment]
@xiyaowong what's broken?

**Comment by ollien** [comment]
Spoke with @xiyaowong, no need to hold the release

https://github.com/vscode-neovim/vscode-neovim/pull/1976#issuecomment-2118876032

**Comment by theol0403** [comment]
:robot: Release is at https://github.com/vscode-neovim/vscode-neovim/releases/tag/v1.11.5 :sunflower:

**Pull request merged**
