### PR TITLE
refactor: set enforced options in Lua

### PR DESCRIPTION
**Pull request by xiyaowong**

### CODE REVIEW

**Comment by theol0403** [comment]
What does this solve? Don't we need to set the forced options *after* the user's init has finished?

**Comment by xiyaowong** [comment]
1. More timely
2. The VimEnter event is executed after loading the vimrc.
3. The purpose of "-S" doesn't belong here originally.
4. I don't see any distinction between this and other modules; there's no need to treat it as a special case within the main_controller.

**Comment by theol0403** [comment]
There is a special distinction. 

The order should be:
- lua modules are loaded (and default options set)
- user config is loaded (which can require("vscode")), which can overwrite default options
- force options are loaded, which **overwrite user options**

**Comment by xiyaowong** [comment]
> Additionally, the autocommand is just for buffer local options, not global options.

👍

**Comment by xiyaowong** [comment]
Currently: default -> force -> user -> force

**Review by theol0403 — APPROVED** [review]
Please test to make sure no behavior is changed.

**Comment by xiyaowong** [comment]
Did a simple test, should be ok.
image

**Pull request merged**
