### PR TITLE
WIP: fix mouse visual mode selection issues

### PR DESCRIPTION
**Pull request by QAston**
Viusual mouse selection mode doesn't work properly on master, the initial click doesn't appear where it's supposed to.

This patch fixes that.

### CODE REVIEW

**Comment by trkoch** [comment]
I gave this a go. This only has any effect with `mouseSelectionStartVisualMode`, right? I wonder, wouldn't it make sense to allow expanding an (existing) visual selection without this setting enabled?

**Comment by QAston** [comment]
Yes, the changes here are only for that setting. Yeah, I think it could be the default, it's probably behind a flag because it's pretty broken.

**Comment by trkoch** [comment]
@justinmk Could we leverage nvim API to expand selection of visual mode with mouse? I'm thinking of entering visual mode with `v` and then clicking somewhere. I'm not aware of a `click` event with line/column in Vscode API though.

**Comment by trkoch** [comment]
Related https://github.com/vscode-neovim/vscode-neovim/pull/1043.

**Pull request closed without merging**
