### PR TITLE
fix: fix mouse double click

### PR DESCRIPTION
**Pull request by windwp**
try to make on double click  working

### CODE REVIEW

**Review by justinmk — DISMISSED** [review]
LGTM

**Comment by trkoch** [comment]
Thanks for your contribution! Can you provide more details? What is this supposed to fix? I doesn't fix double click for me with either mouseSelectionStartVisualMode true/false.

**Comment by windwp** [comment]
sorry i should give more detail.
https://streamable.com/hysyc8
check video i just double click a few time on same place and after that a yellow cursor go to bottom. this PR fix that .

**Comment by theol0403** [comment]
Fix lint please

**Comment by windwp** [comment]
@theol0403  done

**Comment by theol0403** [comment]
Thanks. I'm happy to merge (no regressions), but I've been having trouble understanding and reproducing what this fixes.

**Comment by windwp** [comment]
https://github.com/vscode-neovim/vscode-neovim/issues/891

**Review by theol0403 — APPROVED** [review]

**Pull request merged**
