### PR TITLE
fix: Support inccommand, including "split"

### PR DESCRIPTION
**Pull request by xiyaowong**
fix: wildmenu sometimes not showing

https://github.com/vscode-neovim/vscode-neovim/assets/47070852/46b01ac0-09d7-4866-8c9b-a0a0b40be009

### CODE REVIEW

**Comment by ollien** [comment]
Nice! Use of wildmenu is clever here.

One bug, though I wouldn't say it's a big deal for most cases, is you can't really scroll in this list, either with the arrow keys or the mouse wheel. Are the redraw events being sent repeatedly, or something?

https://github.com/vscode-neovim/vscode-neovim/assets/977151/97097ca3-59ad-4ebe-bac9-7a77dc155bf4

**Comment by xiyaowong** [comment]
It's expected. You can't do anything in nvim's preview window either.

**Review by ollien — APPROVED** [review]

**Comment by ollien** [comment]
@xiyaowong I actually think the quickpick bug I reported above has spread to all other instances of wildmenu. I'm trying to narrow down a cause a bit, but if I come up empty, I'll file a formal issue for it

**Comment by xiyaowong** [comment]
Confirmed.

> I'll file a formal issue for it

No need.

**Pull request merged**
