### PR TITLE
fix(highlight): check highlight with blend for extmark

### LINKED ISSUE #968: Rendering random characters
Random characters are sometimes rendered in place of true characters (the code is still correct when I run it, but doesn't display correctly). If I highlight the wrongly displayed characters and then unhighlight, the error corrects itself. It's really random when it happens and I don't know how best to reproduce it. However, this has happened on two of my machines running Windows 10 and 11. 

Rendered wrong:
image
True text:
image

Rendered wrong:
image
True text:
image

- VS Code Version: 
```
1.68.1
30d9c6cd9483b2cc586687151bcbcd635f373630
x64
```
-VSCode Neovim Version: `v0.0.87`
- OS Version:
```
Edition	Windows 10 Pro
Version	21H2
Installed on	‎3/‎19/‎2021
OS build	19044.1766
Experience	Windows Feature Experience Pack 120.2212.4180.0
```

Steps to Reproduce:

1. Open a python file in VS Code with the "VSCode Neovim" extension
2. Write code for a while, then random characters will be rendered in place of true characters.

https://github.com/microsoft/vscode/issues/154565

### PR DESCRIPTION
**Pull request by windwp**
fix #968

### CODE REVIEW

**Comment by abhiskk** [comment]
I can confirm that this PR resolves the issue for me, thank you @windwp

**Comment by abhiskk** [comment]
hey @theol0403, would it be possible to review-merge this PR in, would really appreciate it.

PS: I have been using the vscode-neovim extension for a month now and really appreciate its importance. Thanks for all the work, @theol0403, @windwp.

**Comment by abhiskk** [comment]
Hi, I would really appreciate if we can get this PR landed. I tried to understand the PR and I have added my comments below. It would be better if the repo owners or the code owners can comment on this, I am trying to be helpful to get this PR in.

From what I can tell previously the extmark overlay was interacting with the search highlights and this PR turns off extmark overlay when the search highlight for characters is on. This setup looks good to me, one follow up question I had was how will the lightspeed highlighting work in this setup, will the lightspeed highlighting be turned off for the regions where search highlighting is on?

**Comment by Shahid-Roofi-Khan** [comment]
Please review and approve this PR. Strange characters het highlighted on screen after simple operations. That's not ideal

**Comment by richyk1** [comment]
This PR is important for the issues many of us using VSCode have been experiencing. I've built this solution on my own computer and it seemed to fix the random letter visual glitch that has been popping up on VSCode when using this Neovim plugin with it. Get this through!

**Comment by theol0403** [comment]
Please people. I am a full time engineering student in the middle of exam season. 

I do this in my free time when I feel like it, and if it weren't for me the project would be dead.

This has been an issue since May. I appreciate the PR.

If you are this impatient for a release, it is very easy to build the PR yourself. If you can't build the PR, download it from CI. Installing it in vscode is trivial.

Sorry for the wait but please don't act entitled to volunteers.

**Review by theol0403 — APPROVED** [review]

**Comment by theol0403** [comment]
Ready to merge. However, this makes a test fail.

@windwp can you fix the test? I'm not sure if the test is correct (this PR breaks something), or if the test is incorrect.

Thanks!

```
 2) Test ext mark
       extmark display overlay:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert_1.default.ok(((_b = (_a = decoration.renderOptions) === null || _a === void 0 ? void 0 : _a.after) === null || _b === void 0 ? void 0 : _b.contentText) == "j")

      + expected - actual

      -false
      +true
      
      at /home/runner/work/vscode-neovim/vscode-neovim/src/test/suite/extmark.test.ts:73:16
```

**Comment by theol0403** [comment]
Tests pass. Thanks!

**Comment by theol0403** [comment]
Oh no! Decided to give a quick test before releasing, and it seems like this breaks leap.nvim for me. 
The virtual text is no longer overlayed as it should be (as you can see, the "leap labels" are just the key underneath).

Could you take a look at this? Let me know if you need help reproducing. Thanks!

image

**Comment by windwp** [comment]
@theol0403  i think  that leap text highlight doesn't have a blend attribute.
https://github.com/windwp/vscode-neovim/blob/46733264c451da0421453a4a215cd8d2a343e569/src/highlight_provider.ts#L208
i check with hop and it have blend attributes on highlight mark  so i use it to reduce a highlight group can overlay.


I just check with leap and it work too :(

**Comment by theol0403** [comment]
Looks like leap does not set the blend attribute. Setting `hi LeapLabelPrimary blend=100` fixes the issue.

I'm not sure if this PR is the right solution to the problem - can you think of another reason for the issues?

Checking for blend seems like a hack and might break compatibility with other plugins (correctly) using extmarks.

**Comment by windwp** [comment]
@theol0403 I remove check blend on that PR .
that issue  come from "Search" highlight group and we already check that
if it have another group have an issue we can add it to ignoredGroupIds. 
So i think we don't need to check attribute blend

**Comment by abhiskk** [comment]
Thank you @theol0403, @windwp for helping with this. Really appreciate it.

**Comment by trkoch** [comment]
> Oh no! Decided to give a quick test before releasing, and it seems like this breaks leap.nvim for me.

@theol0403 @windwp Just wanted to let you know that unfortunately this is still the case for me with 0bf1047. Leap characters shown are not the labels required to jump to.

Commit 0bf1047
image

Release `v0.0.95`
image

**Comment by trkoch** [comment]
This seems to be related to my (local) customization of highlight groups. My motivation was to better match theme colors. Without the highlights leap works as intended.

```json
"vscode-neovim.highlightGroups.highlights": {
    "Cursor": {
      "backgroundColor": "theme.editor.findMatchBackground",
      "borderColor": "theme.editor.findMatchBorder",
      "outlineWidth": "1px",
      "outlineStyle": "solid",
      "outlineColor": "theme.terminal.ansiBrightCyan"
    },
    "LeapLabelPrimary": {
      "backgroundColor": "theme.terminal.ansiBrightCyan",
      "borderColor": "theme.terminal.ansiBrightCyan",
      "color": "#eeeeee"
    }
  },
```

**Comment by trkoch** [comment]
@windwp `addHighlightGroup()` (in `highlight_provider.ts`) ignores names with custom config. Removing the second condition fixes above issue. Can you expand on why this is required? Related to https://github.com/vscode-neovim/vscode-neovim/pull/1100.

```diff
diff --git a/src/highlight_provider.ts b/src/highlight_provider.ts
index ade0fca..bec302a 100644
--- a/src/highlight_provider.ts
+++ b/src/highlight_provider.ts
@@ -205,7 +205,7 @@ export class HighlightProvider {
         const options = this.configuration.highlights[name] || this.configuration.unknownHighlight;
         const conf = options === "vim" ? vimHighlightToVSCodeOptions(vimUiAttrs) : options;
 
-        if (!this.ignoredGroupIds.has(id) && !this.configuration.highlights[name]) {
+        if (!this.ignoredGroupIds.has(id)) {
             this.highlightIdToOverlay.set(id, true);
         }
         this.createDecoratorForHighlightGroup(name, conf);
```

**Comment by windwp** [comment]
@trkoch .This condition checks whether the group name has an ID on the 'highlightIdToOverlay' list, which determines if it is able to display the text overlay(above) of another text.

**Comment by pencilcheck** [comment]
how can I get this fix? i'm on latest (installed directly from marketplace) and still having this issue a lot of times

**Pull request merged**
