### PR TITLE
feat(main): add options.lua

### PR DESCRIPTION
**Pull request by theol0403**
This is the start of moving all vimscript to lua.

I was able to simplify the code a lot by reusing the "force options" function for both global and local functions.

### CODE REVIEW

**Comment by hustrjh** [comment]
Perfect. I'm new to Neovim and it's a little difficult to write lua. Thanks a lot.

**Comment by theol0403** [comment]
@hustrjh what? this has nothing to do with your config

**Comment by hustrjh** [comment]
Aha, sorry for my misunderstanding. But is it possible to provide lua config example in the vault in the future?

**Comment by theol0403** [comment]
@hustrjh you can use lua for your config just like you can with normal neovim

**Comment by hustrjh** [comment]
Thanks. I get it. But it may be more friendly to users if there's some lua examples. I'm a little confused to call vscode command in lua. Here's example in vimscript below.
`xnoremap <C-S-P> <Cmd>call VSCodeNotifyVisual('workbench.action.showCommands', 1)<CR>`

**Comment by theol0403** [comment]
There is no API for that yet. I hope to add one.

**Comment by hustrjh** [comment]
Thanks for your patient reply and your excellent effort. I appreciate it a lot. 😊

**Comment by justinmk** [comment]
> I'm a little confused to call vscode command in lua. Here's example in vimscript below.
> `xnoremap <C-S-P> <Cmd>call VSCodeNotifyVisual('workbench.action.showCommands', 1)<CR>`

vimscript functions can be called from Lua via `:help vim.fn`, e.g.:

    :lua vim.fn['VSCodeNotifyVisual']('workbench.action.showCommands', 1)

But given this PR, something like `require('vscode').notifyvisual(...)` would be nicer.

**Comment by hustrjh** [comment]
@justinmk  Thanks for your advice. 😁

**Pull request merged**
